"""Remove Duplicate Column

Revision ID: 6c18af23aa8c
Revises: aa424abf3a22
Create Date: 2026-06-24 19:59:08.868354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c18af23aa8c'
down_revision: Union[str, None] = 'aa424abf3a22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource_contact', 'subcontractor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_contact', sa.Column('subcontractor', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
