"""Initial Migration

Revision ID: aa424abf3a22
Revises: 
Create Date: 2026-06-24 19:18:14.207458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa424abf3a22'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('for_scaffold', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('py_complaints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('complaint_number', sa.String(length=20), nullable=True),
    sa.Column('stage', sa.Enum('MEMBER_MP_ENQUIRY', 'STAGE_1', 'STAGE_2', 'OMBUDSMAN', name='complaintstage'), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('postcode', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('complaint_number')
    )
    op.create_table('resource',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('subcontractor', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_trade',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trade', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scaffold_checklist_item',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('check_item', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_number', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('postcode', sa.String(length=10), nullable=True),
    sa.Column('complaint_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['py_complaints.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_number')
    )
    op.create_table('resource_contact',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('subcontractor', sa.Boolean(), nullable=True),
    sa.Column('Name', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_stages_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('stages_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['stages_id'], ['job_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scaffold_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('use', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'SENT_TO_COMMERCIAL', 'SENT_TO_RBK', 'APPROVED', 'RISK_ASSESSMENTS', 'PERMIT_TO_ERECT', 'HANDOVER_CHECKS', 'PERMIT_TO_LOAD', 'WORK_COMPLETED', 'OFF_HIRE_NOTICE', 'STRIKE', 'COMPLETED', name='scaffold_stage'), nullable=True),
    sa.Column('resourse_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['resourse_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scaffold_elevations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scaffold_id', sa.UUID(), nullable=False),
    sa.Column('elevation', sa.Enum('FRONT', 'LEFT', 'RIGHT', 'REAR', name='scaffold_elevation'), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('chimney', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['scaffold_id'], ['scaffold_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scaffold_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scaffold_id', sa.UUID(), nullable=False),
    sa.Column('document_name', sa.String(length=60), nullable=False),
    sa.Column('document', sa.LargeBinary(), nullable=False),
    sa.Column('scaffold_checklist_item_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['scaffold_checklist_item_id'], ['scaffold_checklist_item.id'], ),
    sa.ForeignKeyConstraint(['scaffold_id'], ['scaffold_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scaffold_media')
    op.drop_table('scaffold_elevations')
    op.drop_table('scaffold_requests')
    op.drop_table('job_stages_history')
    op.drop_table('resource_contact')
    op.drop_table('jobs')
    op.drop_table('scaffold_checklist_item')
    op.drop_table('roles')
    op.drop_table('resource_trade')
    op.drop_table('resource')
    op.drop_table('py_complaints')
    op.drop_table('job_stages')
    # ### end Alembic commands ###
