"""Adjusted the name of the complaints table as well as the FK on the Jobs table. Capitalized and Singularized class names

Revision ID: b8e4f68ecba6
Revises: 6c18af23aa8c
Create Date: 2026-06-30 19:20:59.237095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8e4f68ecba6'
down_revision: Union[str, None] = '6c18af23aa8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('resource_contact_resource_id_fkey', 'resource_contact', type_='foreignkey')
    op.drop_constraint('scaffold_requests_resourse_id_fkey', 'scaffold_requests', type_='foreignkey')
    op.drop_constraint('scaffold_media_scaffold_checklist_item_id_fkey', 'scaffold_media', type_='foreignkey')
    op.drop_table('resource')
    op.drop_table('scaffold_checklist_item')
    op.drop_table('resource_trade')
    op.drop_table('resource_contact')
    op.create_table('resource_trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trade', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('subcontractor', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scaffold_checklist_items',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('check_item', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('Name', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('complaints', 'address')
    op.drop_column('complaints', 'postcode')
    sa.Enum('REQUEST', 'TG20', 'HANDOVER_CERTIFICATE', 'SCAFFOLD_TAG', 'SCAFFOLD_PIRCTURE', 'INSPECTION', 'OTHER', name='scaffold_media_type').create(op.get_bind())
    op.add_column('scaffold_media', sa.Column('scaffold_media_type', sa.Enum('REQUEST', 'TG20', 'HANDOVER_CERTIFICATE', 'SCAFFOLD_TAG', 'SCAFFOLD_PIRCTURE', 'INSPECTION', 'OTHER', name='scaffold_media_type'), nullable=True))
    
    op.create_foreign_key(None, 'scaffold_media', 'scaffold_checklist_items', ['scaffold_checklist_item_id'], ['id'])
    op.create_foreign_key(None, 'scaffold_requests', 'resources', ['resourse_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scaffold_requests', type_='foreignkey')
    op.create_foreign_key('scaffold_requests_resourse_id_fkey', 'scaffold_requests', 'resource', ['resourse_id'], ['id'])
    op.drop_constraint(None, 'scaffold_media', type_='foreignkey')
    op.create_foreign_key('scaffold_media_scaffold_checklist_item_id_fkey', 'scaffold_media', 'scaffold_checklist_item', ['scaffold_checklist_item_id'], ['id'])
    op.drop_column('scaffold_media', 'scaffold_media_type')
    op.add_column('complaints', sa.Column('postcode', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('complaints', sa.Column('address', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_table('resource_contact',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('Name', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], name='resource_contact_resource_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='resource_contact_pkey')
    )
    op.create_table('resource_trade',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trade', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='resource_trade_pkey')
    )
    op.create_table('scaffold_checklist_item',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('check_item', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='scaffold_checklist_item_pkey')
    )
    op.create_table('resource',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('subcontractor', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='resource_pkey')
    )
    op.drop_table('resource_contacts')
    op.drop_table('scaffold_checklist_items')
    op.drop_table('resources')
    op.drop_table('resource_trades')
    # ### end Alembic commands ###
