"""Adjusted field due to spelling error

Revision ID: d9af6c4e73df
Revises: e743c9c81b72
Create Date: 2026-07-22 18:40:58.454422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9af6c4e73df'
down_revision: Union[str, None] = 'e743c9c81b72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_contacts', sa.Column('name', sa.String(length=60), nullable=False))
    op.drop_column('resource_contacts', 'Name')
    op.add_column('scaffold_requests', sa.Column('resource_id', sa.UUID(), nullable=True))
    op.drop_constraint('scaffold_requests_resourse_id_fkey', 'scaffold_requests', type_='foreignkey')
    op.create_foreign_key(None, 'scaffold_requests', 'resources', ['resource_id'], ['id'])
    op.drop_column('scaffold_requests', 'resourse_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scaffold_requests', sa.Column('resourse_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'scaffold_requests', type_='foreignkey')
    op.create_foreign_key('scaffold_requests_resourse_id_fkey', 'scaffold_requests', 'resources', ['resourse_id'], ['id'])
    op.drop_column('scaffold_requests', 'resource_id')
    op.add_column('resource_contacts', sa.Column('Name', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.drop_column('resource_contacts', 'name')
    # ### end Alembic commands ###
