"""Table & Enum naming conventions

Revision ID: e743c9c81b72
Revises: b8e4f68ecba6
Create Date: 2026-06-30 19:50:33.625691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e743c9c81b72'
down_revision: Union[str, None] = 'b8e4f68ecba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Manually declare and create the new pluralized enum types in Postgres
    complaintstages = postgresql.ENUM('MEMBER_MP_ENQUIRY', 'STAGE_1', 'STAGE_2', 'OMBUDSMAN', name='complaintstages_enum')
    scaffold_elevations = postgresql.ENUM('FRONT', 'LEFT', 'RIGHT', 'REAR', name='scaffold_elevations_enum')
    scaffold_media_types = postgresql.ENUM('REQUEST', 'TG20', 'HANDOVER_CERTIFICATE', 'SCAFFOLD_TAG', 'SCAFFOLD_PIRCTURE', 'INSPECTION', 'OTHER', name='scaffold_media_types_enum')
    scaffold_stages = postgresql.ENUM('REQUESTED', 'SENT_TO_COMMERCIAL', 'SENT_TO_RBK', 'APPROVED', 'RISK_ASSESSMENTS', 'PERMIT_TO_ERECT', 'HANDOVER_CHECKS', 'PERMIT_TO_LOAD', 'WORK_COMPLETED', 'OFF_HIRE_NOTICE', 'STRIKE', 'COMPLETED', name='scaffold_stages_enum')

    complaintstages.create(op.get_bind(), checkfirst=True)
    scaffold_elevations.create(op.get_bind(), checkfirst=True)
    scaffold_media_types.create(op.get_bind(), checkfirst=True)
    scaffold_stages.create(op.get_bind(), checkfirst=True)

    # 2. Run the autogenerated alter commands with explicit PostgreSQL data casting
    op.alter_column('complaints', 'stage',
               existing_type=postgresql.ENUM('MEMBER_MP_ENQUIRY', 'STAGE_1', 'STAGE_2', 'OMBUDSMAN', name='complaintstage'),
               type_=complaintstages,
               existing_nullable=True,
               postgresql_using='stage::text::complaintstages_enum')
               
    op.alter_column('scaffold_elevations', 'elevation',
               existing_type=postgresql.ENUM('FRONT', 'LEFT', 'RIGHT', 'REAR', name='scaffold_elevation'),
               type_=scaffold_elevations,
               existing_nullable=True,
               postgresql_using='elevation::text::scaffold_elevations_enum')
               
    op.alter_column('scaffold_media', 'scaffold_media_type',
               existing_type=postgresql.ENUM('REQUEST', 'TG20', 'HANDOVER_CERTIFICATE', 'SCAFFOLD_TAG', 'SCAFFOLD_PIRCTURE', 'INSPECTION', 'OTHER', name='scaffold_media_type'),
               type_=scaffold_media_types,
               existing_nullable=True,
               postgresql_using='scaffold_media_type::text::scaffold_media_types_enum')
               
    op.alter_column('scaffold_requests', 'status',
               existing_type=postgresql.ENUM('REQUESTED', 'SENT_TO_COMMERCIAL', 'SENT_TO_RBK', 'APPROVED', 'RISK_ASSESSMENTS', 'PERMIT_TO_ERECT', 'HANDOVER_CHECKS', 'PERMIT_TO_LOAD', 'WORK_COMPLETED', 'OFF_HIRE_NOTICE', 'STRIKE', 'COMPLETED', name='scaffold_stage'),
               type_=scaffold_stages,
               existing_nullable=True,
               postgresql_using='status::text::scaffold_stages_enum')

    # 3. Safely clean up the old singular Enum types
    op.execute("DROP TYPE IF EXISTS complaintstage;")
    op.execute("DROP TYPE IF EXISTS scaffold_elevation;")
    op.execute("DROP TYPE IF EXISTS scaffold_media_type;")
    op.execute("DROP TYPE IF EXISTS scaffold_stage;")


def downgrade() -> None:
    # 1. Re-create old singular types if rolling back
    complaintstage = postgresql.ENUM('MEMBER_MP_ENQUIRY', 'STAGE_1', 'STAGE_2', 'OMBUDSMAN', name='complaintstage')
    scaffold_elevation = postgresql.ENUM('FRONT', 'LEFT', 'RIGHT', 'REAR', name='scaffold_elevation')
    scaffold_media_type = postgresql.ENUM('REQUEST', 'TG20', 'HANDOVER_CERTIFICATE', 'SCAFFOLD_TAG', 'SCAFFOLD_PIRCTURE', 'INSPECTION', 'OTHER', name='scaffold_media_type')
    scaffold_stage = postgresql.ENUM('REQUESTED', 'SENT_TO_COMMERCIAL', 'SENT_TO_RBK', 'APPROVED', 'RISK_ASSESSMENTS', 'PERMIT_TO_ERECT', 'HANDOVER_CHECKS', 'PERMIT_TO_LOAD', 'WORK_COMPLETED', 'OFF_HIRE_NOTICE', 'STRIKE', 'COMPLETED', name='scaffold_stage')

    complaintstage.create(op.get_bind(), checkfirst=True)
    scaffold_elevation.create(op.get_bind(), checkfirst=True)
    scaffold_media_type.create(op.get_bind(), checkfirst=True)
    scaffold_stage.create(op.get_bind(), checkfirst=True)

    # 2. Revert the columns
    op.alter_column('scaffold_requests', 'status',
               existing_type=sa.Enum(name='scaffold_stages_enum'),
               type_=scaffold_stage,
               existing_nullable=True,
               postgresql_using='status::text::scaffold_stage')
               
    op.alter_column('scaffold_media', 'scaffold_media_type',
               existing_type=sa.Enum(name='scaffold_media_types_enum'),
               type_=scaffold_media_type,
               existing_nullable=True,
               postgresql_using='scaffold_media_type::text::scaffold_media_type')
               
    op.alter_column('scaffold_elevations', 'elevation',
               existing_type=sa.Enum(name='scaffold_elevations_enum'),
               type_=scaffold_elevation,
               existing_nullable=True,
               postgresql_using='elevation::text::scaffold_elevation')
               
    op.alter_column('complaints', 'stage',
               existing_type=sa.Enum(name='complaintstages_enum'),
               type_=complaintstage,
               existing_nullable=True,
               postgresql_using='stage::text::complaintstage')

    # 3. Clean up the pluralized types
    op.execute("DROP TYPE IF EXISTS complaintstages_enum;")
    op.execute("DROP TYPE IF EXISTS scaffold_elevations_enum;")
    op.execute("DROP TYPE IF EXISTS scaffold_media_types_enum;")
    op.execute("DROP TYPE IF EXISTS scaffold_stages_enum;")
